WARNING: clusterbot not installed. Can't notify slack.
2021-08-12 07:27:41  Turning off  compiler optimizations for fast compilation
                     Suppressing compiler warnings
                     Running with the following prefs combinations:

                     1 run with default preferences
                     

Running tests in /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2, /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/brian2cuda/tests  (including long tests)
Running Brian version 2.2.2.1+git from '/home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2'
Testing standalone

Testing standalone device "cuda_standalone"
Running standalone-compatible standard tests (single run statement)
============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.4, py-1.10.0, pluggy-0.12.0 -- /home/denis/.conda/envs/b2c/bin/python
cachedir: .pytest_cache
rootdir: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository, inifile: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/tests/pytest.ini
collecting ... collected 698 items / 698 deselected

=============================== warnings summary ===============================
/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/mark/structures.py:334
  /home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/mark/structures.py:334: PytestUnknownMarkWarning: Unknown pytest.mark.cuda_standalone - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================== 698 deselected, 1 warnings in 1.89 seconds ==================
Running standalone-compatible standard tests (multiple run statements)
============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.4, py-1.10.0, pluggy-0.12.0 -- /home/denis/.conda/envs/b2c/bin/python
cachedir: .pytest_cache
rootdir: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository, inifile: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/tests/pytest.ini
collecting ... collected 698 items / 698 deselected

======================== 698 deselected in 1.68 seconds ========================
Running standalone-specific tests
============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.4, py-1.10.0, pluggy-0.12.0 -- /home/denis/.conda/envs/b2c/bin/python
cachedir: .pytest_cache
rootdir: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository, inifile: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/tests/pytest.ini
collecting ... collected 698 items / 692 deselected / 6 selected

../../tests/test_gpu_detection.py::test_wrong_cuda_path_error PASSED     [ 16%]
../../tests/test_gpu_detection.py::test_manual_setting_compute_capability PASSED [ 33%]
../../tests/test_gpu_detection.py::test_unsupported_compute_capability_error PASSED [ 50%]
../../tests/test_gpu_detection.py::test_warning_compute_capability_set_twice PASSED [ 66%]
../../tests/test_gpu_detection.py::test_no_gpu_detection_preference_error ('FAILED PROJECT DIRECTORY', <brian2cuda.device.CUDAStandaloneDevice object at 0x7feefe376150>, None)
FAILED [ 83%]
../../tests/test_gpu_detection.py::test_no_gpu_detection_preference PASSED [100%]

=================================== FAILURES ===================================
____________________ test_no_gpu_detection_preference_error ____________________

    @pytest.mark.cuda_standalone
    @pytest.mark.standalone_only
    def test_no_gpu_detection_preference_error():
        set_device("cuda_standalone", directory=None)
        prefs.devices.cuda_standalone.cuda_backend.detect_gpus = False
        # needs setting gpu_id and compute_capability as well
        with pytest.raises(PreferenceError):
>           run(0*ms)
E           Failed: DID NOT RAISE <class 'brian2.core.preferences.PreferenceError'>

../../tests/test_gpu_detection.py:85: Failed
---------------------------- Captured stdout setup -----------------------------

('SETUP_TEARDOWN: set device', 'cuda_standalone', 'with', {'directory': None, 'build_on_run': False, 'with_output': True})
('SETUP_TEARDOWN: project_dir', None)
----------------------------- Captured stdout call -----------------------------
DEBUG DEVICE CUDA build
('DEBUG DEVICE CUDA ensured directory', '/tmp/brian_standalone_dpptU3')
INFO: setting cudaDevice stuff took 0.257269 seconds
objects cu num par blocks 3
INFO: _init_arrays() took 0.088626s
INFO: main_lines took 0.000025 seconds
INFO: main function took 0.346061 seconds
INFO _last_run_time = 9.88131291682e-324 s
============= 1 failed, 5 passed, 692 deselected in 31.07 seconds ==============
ERROR: 3/3 test suite(s) did not complete successfully (see above).
2021-08-12 07:28:15  
TARGET: CUDA_STANDALONE
2021-08-12 07:28:15  
FINISHED ALL RUNS

                     1/1 CONFIGURATIONS FAILED:
                     	1. run
                     		default preferences
Test suite took 0 h 0 m 36 s.
