WARNING: clusterbot not installed. Can't notify slack.
2021-08-12 07:31:48  Turning off  compiler optimizations for fast compilation
                     Suppressing compiler warnings
                     Running with the following prefs combinations:

                     1 run with default preferences
                     

Running tests in /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2, /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/brian2cuda/tests  (including long tests)
Running Brian version 2.2.2.1+git from '/home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2'
Testing standalone

Testing standalone device "cuda_standalone"
Running standalone-compatible standard tests (single run statement)
============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.4, py-1.10.0, pluggy-0.12.0 -- /home/denis/.conda/envs/b2c/bin/python
cachedir: .pytest_cache
rootdir: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository, inifile: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/tests/pytest.ini
collecting ... 	Scalars with units
3 * mV = 3. mV
mV * 3 = 3. mV
3 * mV/mV = 3.0
(23 * metre) ** 2 = 529. m^2
np.sqrt((23 * metre) ** 2) = 23. m
np.sin(2 * np.pi * 100 * Hz * 1 * second) = 3.928773447456944e-15
np.float32(23) * (1 * metre) = 23. m
Expected error raised:  sin expects a dimensionless argument but got 3. s (unit is s).

	Removing units
float(23 * cm) = 0.23
np.float32(23 * cm) = 0.23
np.array(23 * cm) = 0.23
np.asarray(23 * cm) = 0.23

	Arrays with units
np.array([1, 2, 3]) * mV = [1. 2. 3.] mV
np.array([1, 2, 3]) * mV/mV = [1. 2. 3.]
(np.array([1, 2, 3]) * metre) ** 2 = [1. 4. 9.] m^2
np.sqrt((np.array([1, 2, 3]) * metre) ** 2) = [1. 2. 3.] m
np.sin(2 * np.pi * 100 * Hz * np.array([0, 2.5, 5]) * ms) = [ 0.0000000e+00  1.0000000e+00 -3.2162453e-16]
np.array([1, 2, 3], dtype=np.int32) * metre = [1. 2. 3.] m

	removing units
np.asarray(np.array([1, 2, 3]) * metre) = [1. 2. 3.]

	Calculations with unit arrays
np.array([10, 20, 30]) * cm + 1 * metre = [1.1 1.2 1.3] m
np.array([10, 20, 30]) * cm + np.array([1, 2, 3]) * metre = [1.1 2.2 3.3] m
np.array([10, 20, 30]) * cm * (1 / second) = [0.1 0.2 0.3] m s^-1
np.array([10, 20, 30]) * cm * (np.array([1, 2, 3]) / second) = [0.1 0.4 0.9] m s^-1
np.array([10, 20, 30]) * cm / (np.array([1, 2, 3]) * second) = [0.1 0.1 0.1] m s^-1
np.array([10, 20, 30]) * cm * 5 = [0.5 1.  1.5] m
np.ones((3, 4)) * mV = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] mV
(np.ones((3, 4)) * mV).flatten() = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] mV

Unit mismatches
Expected error raised:  Cannot calculate [100. 200. 300.] mm + 3. s, units do not match (units are m and s).
Expected error raised:  Cannot calculate [100. 200. 300.] mm + [1. 2. 3.] s, units do not match (units are m and s).
Expected error raised:  sin expects a dimensionless argument but got [100. 200. 300.] mm (unit is m).

	numpy functions
(np.array([10, 20, 30]) * cm).mean() = 200. mm
np.mean(np.array([10, 20, 30]) * cm) = 200. mm
(np.array([10, 20, 30]) * cm).var() = 6666.66666667 mm^2
np.var(np.array([10, 20, 30]) * cm) = 6666.66666667 mm^2
np.max(np.array([10, 20, 30]) * cm) = 300. mm
np.sum(np.array([10, 20, 30]) * cm) = 0.6 m
np.clip(np.array([10, 20, 30]) * cm, 20 * cm, np.Inf * cm) = [200. 200. 300.] mm

	Comparisons
np.array([10, 20, 30]) * cm == np.array([0.2, 0.2, 0.2]) * metre = [False  True False]
np.array([10, 20, 30]) * cm < np.array([0.2, 0.2, 0.2]) * metre = [ True False False]
Expected error raised:  Cannot perform comparison [100. 200. 300.] mm < [200. 200. 200.] ms, units do not match (units are m and s).

	Slicing and indexing
(np.array([10, 20, 30]) * cm)[:] = [100. 200. 300.] mm
(np.array([10, 20, 30]) * cm)[0:2] = [100. 200.] mm
(np.array([10, 20, 30]) * cm)[0] = 100. mm
(np.array([10, 20, 30]) * cm)[np.array([0, 2])] = [100. 300.] mm
(np.array([10, 20, 30]) * cm)[np.array([True, False, True])] = [100. 300.] mm

	Assigning values
Before assignment:  [100. 200. 300.] mm
After assignment:  [200. 200. 300.] mm
After assignment:  [0.5 0.5 0.3] m
Expected error raised:  Inconsistent units in assignment (units are m and s).
Expected error raised:  Inconsistent units in assignment (units are m and s).

	Conversions to and from list
Quantity([1 * mV, 1 * volt]) = [   1. 1000.] mV
(np.array([1, 2, 3]) * mV).tolist() = [1. * mvolt, 2. * mvolt, 3. * mvolt]

	Examples of functions that are not unit-aware
np.histogram(np.array([1, 2, 3]) * mV) = (array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1]), array([0.001 , 0.0012, 0.0014, 0.0016, 0.0018, 0.002 , 0.0022, 0.0024,
       0.0026, 0.0028, 0.003 ]))
np.correlate(np.array([1, 2, 3]) * mV, np.array([1, 2, 3]) * mV) = [14.] uV
np.trapz(np.array([1, 2, 3]) * mV, np.array([1, 2, 3]) * second) = 4. mWb
np.arange(0 * mV, 10 * mV, 1 * mV) = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] mV
collected 698 items / 698 deselected

=============================== warnings summary ===============================
/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/mark/structures.py:334
  /home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/mark/structures.py:334: PytestUnknownMarkWarning: Unknown pytest.mark.cuda_standalone - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================== 698 deselected, 1 warnings in 2.07 seconds ==================
Running standalone-compatible standard tests (multiple run statements)
============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.4, py-1.10.0, pluggy-0.12.0 -- /home/denis/.conda/envs/b2c/bin/python
cachedir: .pytest_cache
rootdir: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository, inifile: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/tests/pytest.ini
collecting ... collected 698 items / 698 deselected

======================== 698 deselected in 1.86 seconds ========================
Running standalone-specific tests
============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.4, py-1.10.0, pluggy-0.12.0 -- /home/denis/.conda/envs/b2c/bin/python
cachedir: .pytest_cache
rootdir: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository, inifile: /home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/tests/pytest.ini
collecting ... collected 698 items / 692 deselected / 6 selected

../../tests/test_gpu_detection.py::test_wrong_cuda_path_error DEBUG DEVICE CUDA build
('DEBUG DEVICE CUDA ensured directory', '/tmp/brian_standalone_tTgc1S')
PASSED
../../tests/test_gpu_detection.py::test_manual_setting_compute_capability DEBUG DEVICE CUDA build
('DEBUG DEVICE CUDA ensured directory', '/tmp/brian_standalone_4V7v0E')
INFO: setting cudaDevice stuff took 1.061105 seconds
objects cu num par blocks 3
INFO: _init_arrays() took 0.095604s
INFO: main_lines took 0.000036 seconds
INFO: main function took 1.156917 seconds
INFO _last_run_time = 9.88131291682e-324 s
PASSED
../../tests/test_gpu_detection.py::test_unsupported_compute_capability_error DEBUG DEVICE CUDA build
('DEBUG DEVICE CUDA ensured directory', '/tmp/brian_standalone_IiY1WO')
PASSED
../../tests/test_gpu_detection.py::test_warning_compute_capability_set_twice DEBUG DEVICE CUDA build
('DEBUG DEVICE CUDA ensured directory', '/tmp/brian_standalone_DJv4Pm')
INFO: setting cudaDevice stuff took 1.062795 seconds
objects cu num par blocks 3
INFO: _init_arrays() took 0.101101s
INFO: main_lines took 0.000026 seconds
INFO: main function took 1.164109 seconds
INFO _last_run_time = 9.88131291682e-324 s
PASSED
../../tests/test_gpu_detection.py::test_no_gpu_detection_preference_error DEBUG DEVICE CUDA build
('DEBUG DEVICE CUDA ensured directory', '/tmp/brian_standalone_4jikL1')
INFO: setting cudaDevice stuff took 0.261568 seconds
objects cu num par blocks 3
INFO: _init_arrays() took 0.102426s
INFO: main_lines took 0.000027 seconds
INFO: main function took 0.364201 seconds
INFO _last_run_time = 9.88131291682e-324 s

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/main.py", line 250, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/main.py", line 271, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/runner.py", line 78, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/runner.py", line 93, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/_pytest/runner.py", line 175, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/denis/.conda/envs/b2c/lib/python2.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/denis/tubcloud/home/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/conftest.py", line 106, in pytest_runtest_makereport
INTERNALERROR>     print(device.project_dir)
INTERNALERROR> NameError: global name 'device' is not defined

================== 4 passed, 692 deselected in 28.30 seconds ===================
ERROR: 3/3 test suite(s) did not complete successfully (see above).
2021-08-12 07:32:20  
TARGET: CUDA_STANDALONE
2021-08-12 07:32:20  
FINISHED ALL RUNS

                     1/1 CONFIGURATIONS FAILED:
                     	1. run
                     		default preferences
Test suite took 0 h 0 m 33 s.
